const Strings = {
    // routes
    initialRoute: '/',
    signUpRoute: '/sign-up',
    verifyEmailRoute: '/verify-email',
    resetPassowrdRoute: '/reset-password',
    addTickerRoute: '/add-ticker',
    overViewRoute: '/overview',
    zoominRoute: '/zoom-in',

    // api responses
    serverError: 'Server error',
    networkError: 'No internet connection',
    requestTimeOut: 'Request timed out',
    unauthorisedAccess: 'Unauthorized access',
    resourceNotFound: 'Resource not found',
    unknownError: 'Unknown error occurred',
    badRequest: 'Bad request',
    accessForbidden: 'Access forbidden',
    internalServererror: 'Internal server error',
    unexpectedError: 'Unexpected server error',
    requestCancel: 'Request was cancelled',
    pleaseWait: 'Please wait...',

    // static one
    emailAddress: 'Email Address',
    forgetPassword: 'Forgot Password',
    dontHaveAccount: 'Don\'t have account',
    clickHere: 'Click here',
    password: 'Password',
    confirmPassword: 'Confirm Password',
    newPassword: 'New Password',
    signInSubText: 'Sign in to your Pavaki account',
    verifyEmailSubText: 'Enter your registered email address',
    resetPasswordSubText: 'Reset password in your Pavaki account',
    signIn: 'Sign In',
    continue: 'Continue',
    signUp: 'Sign Up',
    or: 'Or',
    signUpSubText: 'Sign up to your Pavaki account',
    manual: 'Manual',
    csvUpload: 'CSV Upload',
    startAnalyzing: 'Start Analyzing',
    addStock: 'Add Stock',
    searchStock: 'Search for stock',
    overview: 'Overview',
    compare: 'Compare',
    exportCSV: 'Export CSV Report',
    exportPDF: 'Export PDF Report',
    pastYear: 'Past Year',
    inputSheet: 'Input Sheet',
    valuation: 'Valuation',
    costCapital: 'Cost of Captial',
    valuationOutput: 'Valuation Output',
    valuationOutputHistorical: 'Valuation Output Historical',
    cfoOI: 'CFO (OI)',
    cfoOILFY: 'CFO (OI) LFY',
    cfoOIHistorical: 'CFO (OI) Historical',
    cfoRevenue: 'CFO Revenue',
    cfoRevenueLfy: 'CFO Revenue LFY',
    cfoRevenueHistorical: 'CFO Revenue Historical',
    fcff: 'FCFF (TTM)',
    fcffLfy: 'FCFF LFY',
    fcffHistorical: 'FCFF Historical',
    companyAnalysis: 'Comapany Analysis',
    rdConverter: 'R_D Converter',
    diagonostics: 'Diagnostics',
    summarySheet: 'Summary Sheet',
    opreatingLease: 'Operating Lease Converter',
    countryEquity: 'Country Equity Risk Premiums',
    syntheticRating: 'Synthetic Rating',
    industryAverageUS: 'Industry Average Beta (US)',
    industryAverageGlobal: 'Industry Average Beta (Global)',
    traling12Month: 'Trailing 12 Month',
    answerKeys: 'Answer Keys',
    propertyValuation: 'Property Valuation',
    storiesNumbers: 'Stories to Numbers',
    optionValue: 'Option value',
    simulationSheet: 'Simulation Sheet',
    yes: 'Yes',
    no: 'No',
}

export default Strings;